# Generated by Django 4.0 on 2022-01-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Advance',
                'verbose_name_plural': 'Advances',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('size', models.CharField(max_length=150, verbose_name='Medida')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('finish_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de finalización')),
                ('start_warranty', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de garantía')),
                ('end_warranty', models.DateTimeField(verbose_name='Fin de garantía')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
