# Generated by Django 4.0 on 2022-01-06 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_end_date_alter_service_end_warranty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 14, 18, 34, 537192), verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='service',
            name='end_warranty',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 14, 18, 34, 537192), verbose_name='Fin de garantía'),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 14, 18, 34, 537192), verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_warranty',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 14, 18, 34, 537192), verbose_name='Inicio de garantía'),
        ),
    ]
