# Generated by Django 4.0 on 2022-01-08 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_end_date_alter_service_end_warranty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 15, 14, 59, 478633), verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='service',
            name='end_warranty',
            field=models.DateTimeField(null=True, verbose_name='Fin de garantía'),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 15, 14, 59, 478633), verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_warranty',
            field=models.DateTimeField(null=True, verbose_name='Inicio de garantía'),
        ),
    ]
