# Generated by Django 4.0 on 2022-01-08 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_end_date_alter_service_end_warranty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='finish_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 17, 30, 27, 84677), verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='service',
            name='finish_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 17, 30, 27, 84677), verbose_name='Fecha de inicio'),
        ),
    ]
