# Generated by Django 4.0 on 2022-01-09 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_ticket_finish_date_alter_service_end_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advance',
            new_name='Payment',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='end_warranty',
        ),
        migrations.RemoveField(
            model_name='service',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='start_warranty',
        ),
        migrations.AddField(
            model_name='service',
            name='reference',
            field=models.CharField(max_length=150, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 9, 17, 9, 85308), verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='end_warranty',
            field=models.DateTimeField(null=True, verbose_name='Fin de garantía'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_warranty',
            field=models.DateTimeField(null=True, verbose_name='Inicio de garantía'),
        ),
        migrations.AlterField(
            model_name='service',
            name='size',
            field=models.CharField(max_length=150, null=True, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de contrato'),
        ),
    ]
