# Generated by Django 4.0 on 2022-01-09 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_rename_advance_payment_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 9, 18, 44, 47296), verbose_name='Fecha de entrega'),
        ),
    ]
