# Generated by Django 4.0 on 2022-01-09 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_ticket_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='reference',
        ),
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 12, 5, 42, 389017), verbose_name='Fecha de entrega'),
        ),
    ]
