# Generated by Django 4.0 on 2022-01-09 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_service_reference_service_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='service',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 12, 59, 0, 113111), verbose_name='Fecha de entrega'),
        ),
    ]
