# Generated by Django 4.0 on 2022-01-09 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_service_address_alter_service_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 14, 9, 2, 585951), verbose_name='Fecha de entrega'),
        ),
    ]
