# Generated by Django 4.0 on 2022-01-13 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_ticket_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 17, 41, 51, 872524), verbose_name='Fecha de entrega'),
        ),
    ]
