# Generated by Django 4.0 on 2022-01-15 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_ticket_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 14, 8, 25, 854538), verbose_name='Fecha de entrega'),
        ),
    ]
