# Generated by Django 4.0 on 2022-01-16 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_rol'),
        ('service', '0018_alter_ticket_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 8, 30, 11, 601778), verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='Usuario'),
        ),
    ]
