# Generated by Django 4.0 on 2022-12-09 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_alter_ticket_end_date_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 17, 5, 16, 620257), verbose_name='Fecha de entrega'),
        ),
    ]
