# Generated by Django 4.0 on 2022-01-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_client_score_alter_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='score',
            field=models.PositiveIntegerField(default=50, verbose_name='Calificación'),
        ),
    ]
