# Generated by Django 4.0 on 2022-01-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_client_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Admin', 'ADMINISTRADOR'), ('Seller', 'SELLER')], default='Seller', max_length=10, verbose_name='Cargo'),
        ),
    ]
