# Generated by Django 4.0 on 2022-01-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Seller', 'Vendedor')], default='Seller', max_length=10, verbose_name='Cargo'),
        ),
    ]
